### PR TITLE
Add string key unit tests to dictionary behaviour tests

### PR DESCRIPTION
**Pull request by danaack**
A string key test has been added for every appropriate int key test already in place.

### CODE REVIEW

**Comment by Stickerpants** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EmSYf7I5&#x2F;189-fix-the-rest-of-the-failing-tests-on-device"> Fix the rest of the failing tests on device</a>

**Comment by Stickerpants** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nx5MbRzu&#x2F;241-fix-b-tree-string-keys"> Fix B+ Tree String keys</a>

**Comment by Stickerpants** [comment]
LGTM

**Comment by wpenson** [comment]
LGTM

**Pull request merged**
